<?php

namespace AppBundle\Repository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends \Doctrine\ORM\EntityRepository
{
	public function dameProductos($brand, $model, $upc, $mpn, $ean) {
		
		$query  = $this->createQueryBuilder('p');
     
		if ($brand && $model) {
			var_dump("1");
			$query->orWhere("(p.marca = '$brand' and p.modelo = '$model' and p.modelo is not null and p.marca is not null)");
		}
		if ($upc) {
			var_dump("2");
			$query->orWhere("p.upc = '$upc' and p.upc is not null");
		}
		if ($mpn) {
			var_dump("3");
			$query->orWhere("p.mpn = '$mpn' and p.mpn is not null");
		}
		if ($ean) {
			var_dump("4");
			$query->orWhere("p.ean = '$ean' and p.ean is not null");
		}
		
		return $query->getQuery()->getResult();
	
	}

}
